services:
  musicbrainz-db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: musicbrainz
      POSTGRES_USER: musicbrainz
      POSTGRES_PASSWORD: musicbrainz
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
